### ISSUE TITLE
Error running dfamscan.pl

### ISSUE THREAD

**Issue by mlathara** [Dfam-consortium/Dfam-Portal#2]
Hello,

I'm not sure this is the right place for this question but...I'm trying to follow the instructions [here](https://github.com/NCIP/ctat-genome-lib-builder/wiki/Building-a-Custom-CTAT-Genome-Lib) to build a custom genome library for quail. However, I'm seeing a failure when that tool invokes `dfamscan.pl`. The error log:

```
* Running CMD: dfamscan.pl -fastafile ref_annot.cdsplus.fa -hmmfile Dfam.hmm -dfam_outfile __dfam_ref_annot.cdsplus.fa/dfam.out --masking_thresh --cpu 20

Error: GA bit thresholds unavailable on model DR0007011

Error running command:
nhmmscan --noali --cut_ga --dfamtblout /tmp/tjaLvacH8Y --cpu=20 Dfam.hmm ref_annot.cdsplus.fa
Error, cmd: dfamscan.pl -fastafile ref_annot.cdsplus.fa -hmmfile Dfam.hmm -dfam_outfile __dfam_ref_annot.cdsplus.fa/dfam.out --masking_thresh --cpu 20 died with ret 6400 No such file or directory at /nfs/home/cctdi/ctat-genome-lib-builder/util/../lib/Pipeliner.pm line 186.
        Pipeliner::run(Pipeliner=HASH(0xa73198)) called at /nfs/home/cctdi/ctat-genome-lib-builder/util/dfam_repeat_masker.pl line 84
```
I think the stuff after `Error: GA bit thresholds unavailable on model DR0007011` has to do with the other tool. The author of that tool suggested asking Dfam group for support...so figured I'd ask here for some insight. Any help is appreciated. Thanks!

**Comment by jebrosen** [comment]
This is something we should fix or document better. This repository includes the help pages on the website, so this is a fine place for this question!

> `Error: GA bit thresholds unavailable on model DR0007011`

With Dfam 3.2 we added support for "uncurated" datasets, under the `DR` accession prefix. These don't go through the same threshold and false discovery rate calcuation as the curated datasets (`DF` prefix), leading to this `GA bit thresholds unavailable` line. I think the culprit here is `--masking_thresh`, which requires the `GA` line. With `DR` families, only an e-value based search is currently supported.

I don't yet have a complete understanding of what that pipeline does, or how the results of `dfamscan.pl` are used, but I am leaning towards one of these two options being the right one in this situation:
* Use the file `Dfam_curatedonly.hmm` instead of `Dfam.hmm`, or use `Dfam.hmm` from an older release. Both files are available at <https://www.dfam.org/releases/Dfam_3.2/families/>.
* Skip the step that requires Dfam. At the time of this writing we only have an ["uncurated" library for Coturnix japonica](https://www.dfam.org/browse?clade=9090&clade_descendants=true&include_raw=true), and it's possible that unresolved false positives and redundancy might impact the overall analysis depending on how it is used.

**Comment by mlathara** [comment]
This is super helpful, thanks!

By digging into Dfam.hmm a bit and reading the HMMER user guide, I was starting to go down the road of trying different thresholding options...but this saves me that effort. One question: If only e-value is available, can I just remove `--masking_thresh` and leave that at default (which I think is e-value?). Of course, I'll check with the author of the other tool if that makes sense as well (I'm not super familiar with what it is using the results of dfamscan.pl, beyond the high level notion that it is doing repeat masking of tranposable elements with it), but wanted to check if there was a reason why you didn't include it as an option.

Thanks again.

**Comment by jebrosen** [comment]
> One question: If only e-value is available, can I just remove --masking_thresh and leave that at default (which I think is e-value?).

dfamscan.pl has the `-E` option for this, accepting an e-value from 0 to 10000. The default is `--annotation_thresh`, which uses `TC` (generated as part of the same procedure as `GA`).

**Comment by mlathara** [comment]
Thanks!
