### ISSUE TITLE
Redundancy between hmms

### ISSUE THREAD

**Issue by isaacmtz12** [Dfam-consortium/Dfam-Portal#3]
Dear developers,
It is mention in the released notes of Dfam 3.3, section 5b. DESCRIPTION OF CHANGES FROM RELEASE 3.1 to 3.2, that you use the 266,740 families from 336 species to build your TE database. I would like to build a small database, as you have done, but with a small set of close related genomes. 
So far, I have the skt files produced with RepeatMasker and the respective hmm files produced with hmmbuild. I would like to know if you have a way to reduce the redundancy between your 266,740 families (within the hmm context) and if so, is the code available?

Also, I would like to know if it is possible to include my hmms in future Dfam versions. 

Thanks for your support. 
Regards,

**Comment by jebrosen** [comment]
> So far, I have the skt files produced with RepeatMasker and the respective hmm files produced with hmmbuild. I would like to know if you have a way to reduce the redundancy between your 266,740 families (within the hmm context) and if so, is the code available?

Resolving redundancy in a database such as Dfam is tricky to do correctly! Models might be duplicated because they are close-but-distinct subfamilies, or because an ancestral element has been independently found in two different species; these situations should be solved differently and it is not always easy to tell which is the case. It is useful, for example, to search for a full-length element in multiple related genomes (or reconstructed ancestral genomes) to determine what clade(s) it can be found in - but this is significantly more computation and work.

To my knowledge this has traditionally been a mostly manual task. Our group has plans for automatically detecting and/or removing some redundancy, but I don't think we have any code or method to share yet; @rmhubley do you have any suggested search parameters or similar that might be a good starting point for doing this on one dataset?

> Also, I would like to know if it is possible to include my hmms in future Dfam versions.

Of course! You can find a submission form on dfam.org after creating an account, or send files to help@dfam.org . In addition to the models themselves, we request a link to the genome they were derived from for processing (preferably a publicly available assembly) and information on the tools used and any additional manual post-processing you have done with the data.
